# Generated by Django 2.2 on 2020-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sermon', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('W', 'Written'), ('V', 'Video from Youtube')], max_length=1)),
                ('youtube_video_id', models.URLField(blank=True, verbose_name='Youtube Video Url')),
                ('date', models.DateField(auto_now_add=True)),
                ('preached_by', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='sermons/')),
                ('website', models.BooleanField(default=True, help_text='Publish on the website')),
                ('preached_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
