# Generated by Django 2.2 on 2019-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='sermons/'),
        ),
    ]
