# Generated by Django 2.2 on 2019-04-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='preaced_by_member',
            new_name='preached_by_member',
        ),
    ]
