# Generated by Django 2.2 on 2019-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_auto_20190520_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
