# Generated by Django 2.2 on 2019-06-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_auto_20190605_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preached_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preached_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
