# Generated by Django 2.2 on 2019-05-31 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20190504_0858'),
        ('groups', '0004_auto_20190419_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(help_text='the app this message was sent from', max_length=160)),
                ('message', models.CharField(max_length=160)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of publishing of the message')),
                ('website', models.BooleanField(default=True, help_text='Publish on the website')),
                ('church_group', models.ManyToManyField(blank=True, to='groups.ChurchGroup')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='smsReceipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipient', to='member.Member')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Sms')),
            ],
        ),
        migrations.CreateModel(
            name='smsReceipientGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipient_group', to='sms.Sms')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Sms')),
            ],
        ),
        migrations.AddField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.smsReceipients', to='member.Member'),
        ),
        migrations.AddField(
            model_name='sms',
            name='sending_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_member', to='member.Member'),
        ),
    ]
