# Generated by Django 2.2 on 2020-01-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipientgroups',
            name='receipient_group',
        ),
        migrations.RemoveField(
            model_name='smsreceipientgroups',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='smsreceipients',
            name='receipient',
        ),
        migrations.RemoveField(
            model_name='smsreceipients',
            name='sms',
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
        migrations.DeleteModel(
            name='SmsReceipientGroups',
        ),
        migrations.DeleteModel(
            name='SmsReceipients',
        ),
    ]
