# Generated by Django 2.2 on 2019-06-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20190601_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='church_group',
            new_name='church_groups',
        ),
        migrations.AlterField(
            model_name='sms',
            name='app',
            field=models.CharField(default='api', help_text='the app this message was sent from', max_length=160),
        ),
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
