# Generated by Django 2.2 on 2019-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190601_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='app',
            field=models.CharField(default='admin', help_text='the app this message was sent from', max_length=160),
        ),
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
