# Generated by Django 2.2 on 2020-01-23 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20200123_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipients',
            name='date',
        ),
        migrations.AddField(
            model_name='smsreceipients',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 12, 47, 3, 853950)),
        ),
    ]
