# Generated by Django 2.2 on 2020-01-23 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20200123_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipients',
            name='time',
        ),
        migrations.AddField(
            model_name='smsreceipients',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 12, 54, 12, 181975)),
        ),
    ]
