# Generated by Django 2.2 on 2019-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190601_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreceipients',
            name='cost',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='smsreceipients',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
