# Generated by Django 2.2 on 2020-01-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20200123_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipients',
            name='date',
        ),
    ]
