# Generated by Django 2.2 on 2020-01-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_smsreceipients_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipients',
            name='date',
        ),
    ]
