# Generated by Django 2.2 on 2020-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_remove_smsreceipients_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreceipients',
            name='cost',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
