# Generated by Django 2.2 on 2020-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_smsreceipients_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsreceipients',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
