# Generated by Django 2.2 on 2020-01-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsreceipients_date'),
        ('sms', '0012_auto_20200127_1245'),
    ]

    operations = [
    ]
