# Generated by Django 2.2 on 2020-01-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_merge_20200128_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreceipients',
            name='date',
        ),
    ]
