# Generated by Django 2.2 on 2020-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_remove_smsreceipients_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
