# Generated by Django 2.2 on 2019-06-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_auto_20190621_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
