# Generated by Django 2.2 on 2019-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_auto_20190622_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
