# Generated by Django 2.2 on 2019-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0037_auto_20190703_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='receipients',
            field=models.ManyToManyField(through='sms.SmsReceipients', to='member.Member'),
        ),
    ]
