# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='SEO friendly slug', unique=True)),
                ('description', models.TextField(help_text='Description of the event')),
                ('date', models.DateTimeField(help_text='Date and Time of the event')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('website', models.BooleanField(default=True, help_text='Display on the website')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events')),
                ('location', models.CharField(help_text='The location of the event ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='fellowships/')),
            ],
        ),
        migrations.CreateModel(
            name='EventRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedToAttendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
