# Generated by Django 2.2 on 2020-03-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
    ]
