# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='cell_groups_coming',
            field=models.ManyToManyField(blank=True, to='groups.CellGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='church_groups_coming',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='fellowships_coming',
            field=models.ManyToManyField(blank=True, to='groups.Fellowship'),
        ),
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='ministries_coming',
            field=models.ManyToManyField(blank=True, to='groups.Ministry'),
        ),
    ]
