# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20190406_1018'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedtoattendevent',
            name='who_is_coming',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
        migrations.AddField(
            model_name='eventroster',
            name='attendee_members',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
        migrations.AddField(
            model_name='eventroster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='event_attendees',
            field=models.ManyToManyField(blank=True, to='events.EventRoster'),
        ),
    ]
