# Generated by Django 2.2 on 2019-08-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190821_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='eventattendance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='event_attendees',
        ),
        migrations.RemoveField(
            model_name='eventroster',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='eventroster',
            name='event',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='cell_groups_coming',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='church_groups_coming',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='fellowships_coming',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='ministries_coming',
        ),
        migrations.RemoveField(
            model_name='expectedtoattendevent',
            name='who_is_coming',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAttendance',
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
        migrations.DeleteModel(
            name='EventRoster',
        ),
        migrations.DeleteModel(
            name='ExpectedToAttendEvent',
        ),
    ]
