# Generated by Django 2.2 on 2020-01-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_churchgroup_anvil_space_only'),
        ('member', '0007_auto_20200128_1759'),
        ('events', '0010_merge_20200128_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttendingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='MemberThatAttendedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventattendinggroup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattendinggroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='EventAttendedMember',
        ),
        migrations.DeleteModel(
            name='EventAttendingGroup',
        ),
    ]
