# Generated by Django 2.2 on 2019-04-08 09:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=100)),
                ('start', models.DateField(help_text='Start date of the project', verbose_name='Starting Date')),
                ('stop', models.DateField(help_text='Completion date of the project', verbose_name='Completion Date')),
                ('description', models.TextField(help_text='Description of the project')),
                ('required_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('raised_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='This is cumulatively added when members bring in contributions or contribution from another place, e.g a fundraising', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('church_group', models.ManyToManyField(help_text='The church groups this project belongs to.', to='groups.ChurchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, help_text="If the person pledging is not a church member, record their names. You can't record a name and also have a member.Record only one.", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='If the person pledging is not a member, record their phone number', max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(verbose_name='Pledge Payment Date')),
                ('details', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payed_on', models.DateField(null=True)),
                ('payed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payed', models.BooleanField(default=False, verbose_name='payment complete')),
                ('narration', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, help_text="If the person pledging is church member,Select them from the list,If not record their names. You can't record a name and also have a member.Record only one.", null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('payment_recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_by', to='member.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_recorded_by', to='member.Member')),
            ],
        ),
    ]
