# Generated by Django 2.2 on 2019-05-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='details',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='payed_amount',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='payed_on',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='payment_recorded_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='raised_amount',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_on', models.DateField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('Pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('payment_recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_recorded_by', to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('anonymous', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='member.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.Project')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_recorded_bys', to='member.Member')),
            ],
        ),
    ]
