# Generated by Django 2.2 on 2019-11-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_delete_client'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_message', models.TextField(max_length=500)),
                ('type', models.CharField(blank=True, choices=[('C', 'Contribution'), ('P', 'PledgeSettlement')], max_length=2, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirming_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirming_for', to='member.Member')),
                ('for_pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Pledge')),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_projects', to='projects.Project')),
            ],
        ),
    ]
