# Generated by Django 2.2 on 2019-05-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190502_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgepayment',
            name='payment_on',
        ),
    ]
