# Generated by Django 2.2 on 2019-11-26 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pendingconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingconfirmation',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='pendingconfirmation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='for_pledge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Pledge'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='for_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_projects', to='projects.Project'),
        ),
    ]
