# Generated by Django 2.2 on 2019-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_pledgepayment_payment_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgepayment',
            old_name='Pledge',
            new_name='pledge',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
