# Generated by Django 2.2 on 2019-11-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191126_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingconfirmation',
            name='for_pledge',
        ),
    ]
