# Generated by Django 2.2 on 2019-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_pendingconfirmation_for_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconfirmation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
