# Generated by Django 2.2 on 2019-05-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190504_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgepayment',
            old_name='recorded_at',
            new_name='payment_recorded_on',
        ),
    ]
