# Generated by Django 2.2 on 2019-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190504_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='church_group',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
    ]
