# Generated by Django 2.2 on 2019-07-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190619_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ('-recorded_at',)},
        ),
    ]
