# Generated by Django 2.2 on 2019-04-12 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='The heading title of the news article', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('article', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of publishing of the article')),
                ('author', models.CharField(help_text='Author of the news article', max_length=100)),
                ('website', models.BooleanField(default=True, help_text='Publish on the website')),
                ('church_group', models.ManyToManyField(help_text='The church groups this news is intended for.', to='groups.ChurchGroup')),
                ('fellowship', models.ManyToManyField(to='groups.Fellowship')),
                ('ministry', models.ManyToManyField(to='groups.Ministry')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ('-date',),
            },
        ),
    ]
