# Generated by Django 2.2 on 2019-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='fellowship',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ministry',
        ),
    ]
