# Generated by Django 2.2 on 2019-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='news',
            name='church_group',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fellowship',
            field=models.ManyToManyField(blank=True, to='groups.Fellowship'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ministry',
            field=models.ManyToManyField(blank=True, to='groups.Ministry'),
        ),
    ]
