# Generated by Django 2.2 on 2019-05-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190504_0858'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='member',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='titheparent',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='PledgePayment',
        ),
        migrations.RemoveField(
            model_name='tithe',
            name='parent',
        ),
        migrations.AddField(
            model_name='offering',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Family'),
        ),
        migrations.AddField(
            model_name='offering',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='offering',
            name='name_if_not_member',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='church_group',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='TitheParent',
        ),
    ]
