# Generated by Django 2.2 on 2020-03-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200311_1411'),
        ('services', '0003_auto_20200305_1512'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='tithe',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
