# Generated by Django 2.2 on 2020-01-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        ('member', '0006_auto_20200109_1301'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='church_group',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='offering',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='offering',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_recorded_by', to='member.Member'),
        ),
        migrations.AddField(
            model_name='offering',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AddField(
            model_name='income',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_recorded_by', to='member.Member'),
        ),
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.IncomeType'),
        ),
        migrations.AddField(
            model_name='groupoffering',
            name='church_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='groupoffering',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Offering'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_recorded_by', to='member.Member'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ExpenditureType'),
        ),
    ]
