# Generated by Django 2.2 on 2020-03-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200311_1411'),
        ('finance', '0002_auto_20200311_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='church_group',
        ),
        migrations.AddField(
            model_name='offering',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.DeleteModel(
            name='GroupOffering',
        ),
    ]
