# Generated by Django 2.2 on 2019-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190504_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitheStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
