# Generated by Django 2.2 on 2019-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_pendingconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingconfirmation',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='pendingconfirmation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
