# Generated by Django 2.2 on 2019-05-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expenditurestats_incomestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenditureStats',
        ),
        migrations.DeleteModel(
            name='IncomeStats',
        ),
        migrations.DeleteModel(
            name='TitheStats',
        ),
    ]
