# Generated by Django 2.2 on 2019-11-26 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20191126_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconfirmation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
