# Generated by Django 2.2 on 2019-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20190509_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
