# Generated by Django 2.2 on 2020-01-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200128_1745'),
        ('finance', '0005_pendingconfirmation_date'),
    ]

    operations = [
    ]
