# Generated by Django 2.2 on 2019-05-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190523_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='family',
        ),
    ]
