# Generated by Django 2.2 on 2020-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200129_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituretype',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
    ]
