# Generated by Django 2.2 on 2019-06-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190605_0751'),
        ('finance', '0007_remove_offering_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Offering')),
            ],
        ),
    ]
