# Generated by Django 2.2 on 2019-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_groupoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
