# Generated by Django 2.2 on 2020-02-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200207_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
