# Generated by Django 2.2 on 2020-02-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20200212_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
