# Generated by Django 2.2 on 2019-06-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20190605_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
