# Generated by Django 2.2 on 2020-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20200212_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
