# Generated by Django 2.2 on 2019-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20190605_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
