# Generated by Django 2.2 on 2020-02-12 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20200212_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
