# Generated by Django 2.2 on 2019-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_tithe_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
