# Generated by Django 2.2 on 2019-07-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190629_1116'),
        ('finance', '0014_auto_20190622_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='expendituretype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
