# Generated by Django 2.2 on 2019-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.TextField(blank=True)),
                ('CheckoutRequestID', models.TextField(blank=True)),
                ('ResultCode', models.TextField(blank=True)),
                ('ResultDesc', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('MpesaReceiptNumber', models.TextField(blank=True)),
                ('TransactionDate', models.DateField(blank=True, null=True)),
                ('PhoneNumber', models.TextField(blank=True)),
                ('Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
