# Generated by Django 2.2 on 2019-05-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Date and Time of the event'),
        ),
    ]
