# Generated by Django 2.2 on 2019-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_remove_event_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='default_past',
            field=models.BooleanField(default=False),
        ),
    ]
