# Generated by Django 2.2 on 2019-05-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_default_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='default_past',
        ),
    ]
