# Generated by Django 2.2 on 2019-11-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_delete_client'),
        ('church_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.CharField(max_length=1600),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='DiscussionReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, choices=[('L', 'Like'), ('R', 'Reccomend'), ('H', 'Heart')], max_length=2, null=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_social.Discussion')),
                ('reaction_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
