# Generated by Django 2.2 on 2019-10-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190822_1433'),
        ('church_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PeerToPeerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_to_peer_receiver', to='member.Member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_to_peer_sender', to='member.Member')),
            ],
        ),
    ]
