# Generated by Django 2.2 on 2019-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreaction',
            name='recommendation',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
