# Generated by Django 2.2 on 2019-10-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_social', '0002_auto_20191029_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertopeermessage',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
