# Generated by Django 2.2 on 2019-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_social', '0003_auto_20191120_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
