# Generated by Django 2.2 on 2019-08-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_group_memberships', to='groups.ChurchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(default='none', help_text='The day of the service', max_length=100, null=True)),
                ('date', models.DateField(default='2019-05-01', help_text='The day of the service', null=True)),
                ('start', models.TimeField(help_text='write time e.g 00:22:19', null=True)),
                ('end', models.TimeField(help_text='write time e.g 00:22:19', null=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the church service', max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('church_groups', models.ManyToManyField(through='services.ChurchGroupMembership', to='groups.ChurchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Title of the action to be performed', max_length=100)),
                ('value', models.CharField(help_text='The value to the title', max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='churchgroupmembership',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_group_memberships', to='services.ServiceType'),
        ),
    ]
