# Generated by Django 2.2 on 2019-06-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the church service', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Title of the action to be performed', max_length=100)),
                ('value', models.CharField(help_text='The value to the title', max_length=200)),
                ('venue', models.CharField(default='none', help_text='The day of the service', max_length=100)),
                ('date', models.DateField(default='2019-05-01', help_text='The day of the service')),
                ('start', models.TimeField(help_text='write time e.g 00:22:19')),
                ('end', models.TimeField(help_text='write time e.g 00:22:19')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
