# Generated by Django 2.2 on 2019-04-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the church service', max_length=150)),
                ('date', models.DateField(help_text='The day of the service')),
                ('church_group', models.ManyToManyField(help_text='The church groups this service is intended for.', to='groups.ChurchGroup')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Title of the action to be performed', max_length=100)),
                ('value', models.CharField(help_text='The value to the title', max_length=200)),
                ('start', models.TimeField(help_text='write time e.g 00:22:19')),
                ('end', models.TimeField(help_text='write time e.g 00:22:19')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
