# Generated by Django 2.2 on 2020-02-24 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
