# Generated by Django 2.2 on 2020-03-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='church_groups',
        ),
        migrations.DeleteModel(
            name='ChurchGroupMembership',
        ),
    ]
