# Generated by Django 2.2 on 2019-06-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190605_0751'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_group_memberships', to='groups.ChurchGroup')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_group_memberships', to='services.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='church_groups',
            field=models.ManyToManyField(through='services.ChurchGroupMembership', to='groups.ChurchGroup'),
        ),
    ]
