# Generated by Django 2.2 on 2019-06-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190605_0751'),
        ('services', '0002_auto_20190629_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the church service', max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='church_groups',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='end',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='start',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='venue',
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default='2019-05-01', help_text='The day of the service', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end',
            field=models.TimeField(help_text='write time e.g 00:22:19', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start',
            field=models.TimeField(help_text='write time e.g 00:22:19', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='venue',
            field=models.CharField(default='none', help_text='The day of the service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='churchgroupmembership',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_group_memberships', to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='church_groups',
            field=models.ManyToManyField(through='services.ChurchGroupMembership', to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType'),
        ),
    ]
