# Generated by Django 2.2 on 2019-07-03 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190703_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
