# Generated by Django 2.2 on 2019-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
