# Generated by Django 2.2 on 2020-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('ID_number', models.CharField(default='demo', max_length=8)),
                ('phone_number', models.CharField(default='demo', max_length=15)),
                ('city_or_town', models.CharField(default='demo', max_length=20)),
                ('road_or_street', models.CharField(default='demo', max_length=20)),
                ('location_description', models.CharField(default='demo', max_length=100)),
                ('website', models.CharField(blank=True, default='demo', max_length=50, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('last_credited', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=150)),
                ('vision', models.TextField(max_length=150)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSMSCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_username', models.CharField(default='sandbox', max_length=50)),
                ('at_api_key', models.CharField(default='ec15ef7d7316dc2c55b263914fdc7f57bbb6ff484fc37c83ad1a1d0e80f24bfa', max_length=150)),
                ('at_mpesa_acc_no', models.CharField(blank=True, default='demo.api', max_length=50, null=True)),
                ('at_mpesa_paybill', models.CharField(blank=True, default='525900', max_length=20, null=True)),
                ('at_sender_id', models.CharField(blank=True, default='AFRICASTKNG', max_length=20, null=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitorID', models.CharField(blank=True, max_length=50, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchPeriodicTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='ChurchLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchCoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=20)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
