# Generated by Django 2.2 on 2020-02-28 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsmscredentials',
            name='at_api_key',
            field=models.CharField(default='ec15ef7d7316dc2c55b263914fdc7f57bbb6ff484fc37c83ad1a1d0e80f24bfa', max_length=150),
        ),
        migrations.AlterField(
            model_name='churchsmscredentials',
            name='at_username',
            field=models.CharField(default='sandbox', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 28, 23, 1, 52, 916820)),
        ),
    ]
