# Generated by Django 2.2 on 2020-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
