# Generated by Django 2.2 on 2019-12-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_client_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('ID_number', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=15)),
                ('city_or_town', models.CharField(max_length=20)),
                ('road_or_street', models.CharField(max_length=20)),
                ('location_description', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
