# Generated by Django 2.2 on 2020-02-29 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20200228_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 29, 11, 44, 31, 294563)),
        ),
    ]
