# Generated by Django 2.2 on 2020-02-29 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20200229_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 29, 11, 46, 23, 458005)),
        ),
    ]
