# Generated by Django 2.2 on 2020-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_churchsitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsmscredentials',
            name='at_sender_id',
            field=models.CharField(blank=True, default='AFRICASTKNG', max_length=20, null=True),
        ),
    ]
