# Generated by Django 2.2 on 2020-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_clientcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.DeleteModel(
            name='ClientCredit',
        ),
    ]
