# Generated by Django 2.2 on 2020-03-02 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_auto_20200229_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsmscredentials',
            name='at_mpesa_acc_no',
            field=models.CharField(blank=True, default='demo.api', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='churchsmscredentials',
            name='at_mpesa_paybill',
            field=models.CharField(blank=True, default='525900', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 2, 12, 10, 23, 930951)),
        ),
    ]
