# Generated by Django 2.2 on 2020-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20200119_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='ID_number',
            field=models.CharField(default='demo', max_length=8),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='city_or_town',
            field=models.CharField(default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='location_description',
            field=models.CharField(default='demo', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='phone_number',
            field=models.CharField(default='demo', max_length=15),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='road_or_street',
            field=models.CharField(default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='website',
            field=models.CharField(blank=True, default='demo', max_length=50, null=True),
        ),
    ]
