# Generated by Django 2.2 on 2020-03-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20200302_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='last_credited',
        ),
    ]
