# Generated by Django 2.2 on 2020-01-22 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_auto_20200119_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 22, 21, 33, 1, 959433)),
        ),
    ]
