# Generated by Django 2.2 on 2020-01-23 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0017_auto_20200123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 14, 5, 37, 847746)),
        ),
    ]
