# Generated by Django 2.2 on 2020-01-29 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0036_auto_20200128_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 29, 12, 21, 39, 336865)),
        ),
    ]
