# Generated by Django 2.2 on 2020-02-10 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0038_auto_20200207_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 10, 11, 53, 13, 396358)),
        ),
    ]
