# Generated by Django 2.2 on 2020-02-12 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0045_auto_20200212_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 12, 15, 47, 5, 913360)),
        ),
    ]
