# Generated by Django 2.2 on 2020-02-12 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0046_auto_20200212_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 12, 15, 48, 2, 452446)),
        ),
    ]
