# Generated by Django 2.2 on 2020-02-17 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0050_auto_20200212_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='sms_quota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 17, 13, 41, 18, 220894)),
        ),
    ]
