# Generated by Django 2.2 on 2020-02-24 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0052_auto_20200224_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 24, 17, 50, 6, 539696)),
        ),
    ]
