# Generated by Django 2.2 on 2020-02-26 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0053_auto_20200224_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchcorevalue',
            old_name='client',
            new_name='church',
        ),
        migrations.RenameField(
            model_name='churchlogo',
            old_name='client',
            new_name='church',
        ),
        migrations.RenameField(
            model_name='churchperiodictheme',
            old_name='client',
            new_name='church',
        ),
        migrations.RenameField(
            model_name='churchstatement',
            old_name='client',
            new_name='church',
        ),
        migrations.RenameField(
            model_name='churchstatement',
            old_name='vission',
            new_name='vision',
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='last_credited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 26, 13, 23, 34, 2975)),
        ),
        migrations.CreateModel(
            name='ChurchAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
