# Generated by Django 2.2 on 2019-04-05 09:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('role', models.ForeignKey(default=member.models.Role.get_role, on_delete=django.db.models.deletion.CASCADE, to='member.Role')),
            ],
        ),
        migrations.CreateModel(
            name='MemberResidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(blank=True, max_length=200, verbose_name='Residence/Estate')),
                ('road', models.CharField(blank=True, max_length=200, verbose_name='Road/Street')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal', models.CharField(blank=True, max_length=200, verbose_name='Postal Address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telephone(Mobile)')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact No.')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
