# Generated by Django 2.2 on 2019-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gender'], name='member_memb_gender_02dd3f_idx'),
        ),
    ]
