# Generated by Django 2.2 on 2019-04-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='members',
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Family')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
