# Generated by Django 2.2 on 2019-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMember',
            new_name='FamilyMembership',
        ),
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(through='member.FamilyMembership', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='membermaritalstatus',
            name='status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=2, null=True),
        ),
    ]
