# Generated by Django 2.2 on 2019-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190821_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='importantdatetype',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='description',
            field=models.CharField(blank=True, max_length=30, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='road',
            field=models.CharField(blank=True, max_length=15, verbose_name='Road'),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='street',
            field=models.CharField(blank=True, max_length=15, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='town',
            field=models.CharField(blank=True, max_length=15, verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='village_estate',
            field=models.CharField(blank=True, max_length=15, verbose_name='village/estate'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
