# Generated by Django 2.2 on 2019-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190411_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather not say')], max_length=2, null=True),
        ),
    ]
