# Generated by Django 2.2 on 2019-04-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_family_memberfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='family',
            name='head',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyHeads', to='member.Member'),
        ),
        migrations.DeleteModel(
            name='MemberFamily',
        ),
    ]
