# Generated by Django 2.2 on 2019-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190618_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='site_adminstration',
            field=models.BooleanField(default=False),
        ),
    ]
