# Generated by Django 2.2 on 2019-06-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_role_site_adminstration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='site_adminstration',
        ),
        migrations.AddField(
            model_name='role',
            name='event_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='finance_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='group_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='member_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='projects_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
