# Generated by Django 2.2 on 2019-11-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
