# Generated by Django 2.2 on 2020-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
