# Generated by Django 2.2 on 2020-01-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200109_1301'),
    ]

    operations = [
    ]
