# Generated by Django 2.2 on 2019-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
