# Generated by Django 2.2 on 2019-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
