# Generated by Django 2.2 on 2020-02-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20200128_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=160)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mote_for', to='member.Member')),
                ('note_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_by', to='member.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='siblingrelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='siblingrelation',
            name='sibling',
        ),
        migrations.RemoveField(
            model_name='spouserelation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='spouserelation',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='family',
            name='head',
        ),
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membercontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='membercontact',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='memberresidence',
            name='village_estate',
        ),
        migrations.AddField(
            model_name='membercontact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone(Mobile)'),
        ),
        migrations.DeleteModel(
            name='ParentRelation',
        ),
        migrations.DeleteModel(
            name='SiblingRelation',
        ),
        migrations.DeleteModel(
            name='SpouseRelation',
        ),
    ]
