# Generated by Django 2.2 on 2020-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20200210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberage',
            name='d_o_b',
            field=models.DateField(null=True),
        ),
    ]
