# Generated by Django 2.2 on 2019-07-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20190712_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SiblingRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('sibling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ParentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dads', to='member.Member')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moms', to='member.Member')),
            ],
        ),
    ]
