# Generated by Django 2.2 on 2019-07-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_parentrelation_siblingrelation_spouserelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='MemberImportantDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('overseen_by_non_member', models.CharField(blank=True, max_length=50, null=True)),
                ('non_member_description', models.CharField(blank=True, max_length=160, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('overseen_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overseer', to='member.Member')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.ImportantDateType')),
            ],
        ),
    ]
