# Generated by Django 2.2 on 2020-02-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20200210_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberage',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='membermaritalstatus',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
