# Generated by Django 2.2 on 2020-02-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20200210_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontact',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
