# Generated by Django 2.2 on 2019-07-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_importantdatetype_memberimportantdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentrelation',
            name='dad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dads', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='parentrelation',
            name='mom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moms', to='member.Member'),
        ),
    ]
