# Generated by Django 2.2 on 2020-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20200210_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberresidence',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='road',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='street',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='memberresidence',
            name='town',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
