# Generated by Django 2.2 on 2020-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20200212_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberresidence',
            name='village_estate',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
