# Generated by Django 2.2 on 2020-02-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_memberresidence_village_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontact',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='membercontact',
            name='phone2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
