# Generated by Django 2.2 on 2019-04-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Duties',
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.Duty')),
                ('members', models.ManyToManyField(blank=True, to='member.Member')),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Roster',
            },
        ),
    ]
