# Generated by Django 2.2 on 2019-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyroster',
            name='member',
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='members',
            field=models.ManyToManyField(to='member.Member'),
        ),
    ]
