# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyroster',
            name='members',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
