# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedToReceiveVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual reading')),
                ('verse', models.CharField(help_text='The verse in the Bible', max_length=200)),
                ('day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
