# Generated by Django 2.2 on 2019-04-08 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual reading')),
                ('verse', models.CharField(help_text='The verse in the Bible', max_length=200)),
                ('day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedToReceiveVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_groups_receiving', models.ManyToManyField(blank=True, to='groups.CellGroup')),
                ('church_groups_receiving', models.ManyToManyField(blank=True, to='groups.ChurchGroup')),
                ('fellowships_receiving', models.ManyToManyField(blank=True, to='groups.Fellowship')),
                ('ministries_receiving', models.ManyToManyField(blank=True, to='groups.Ministry')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.Verse')),
                ('who_will_receive', models.ManyToManyField(blank=True, to='member.Member')),
            ],
        ),
    ]
