# Generated by Django 2.2 on 2019-05-20 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyVerses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='lesson',
            field=models.TextField(default=django.utils.timezone.now, help_text='a lesson or moral from the verse'),
            preserve_default=False,
        ),
    ]
