# Generated by Django 2.2 on 2020-01-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('dailyVerses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipientgroup',
            name='receipient_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='receipientgroup',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.ExpectedToReceiveVerse'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='church_groups_receiving',
            field=models.ManyToManyField(blank=True, through='dailyVerses.ReceipientGroup', to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.Verse'),
        ),
    ]
