# Generated by Django 2.2 on 2019-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyVerses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipientfellowship',
            name='receipient_fellowship',
        ),
        migrations.RemoveField(
            model_name='receipientfellowship',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='receipientministry',
            name='receipient_ministry',
        ),
        migrations.RemoveField(
            model_name='receipientministry',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='expectedtoreceiveverse',
            name='cell_groups_receiving',
        ),
        migrations.RemoveField(
            model_name='expectedtoreceiveverse',
            name='fellowships_receiving',
        ),
        migrations.RemoveField(
            model_name='expectedtoreceiveverse',
            name='ministries_receiving',
        ),
        migrations.RemoveField(
            model_name='expectedtoreceiveverse',
            name='who_will_receive',
        ),
        migrations.DeleteModel(
            name='ReceipientCellGroup',
        ),
        migrations.DeleteModel(
            name='ReceipientFellowship',
        ),
        migrations.DeleteModel(
            name='ReceipientMinistry',
        ),
    ]
