# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('dailyVerses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='cell_groups_receiving',
            field=models.ManyToManyField(blank=True, to='groups.CellGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='church_groups_receiving',
            field=models.ManyToManyField(blank=True, to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='fellowships_receiving',
            field=models.ManyToManyField(blank=True, to='groups.Fellowship'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='ministries_receiving',
            field=models.ManyToManyField(blank=True, to='groups.Ministry'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.Verse'),
        ),
    ]
