# Generated by Django 2.2 on 2019-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailyVerses', '0002_auto_20190406_1018'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='who_will_receive',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
