# Generated by Django 2.2 on 2020-01-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyVerses', '0002_auto_20200128_1745'),
        ('dailyVerses', '0002_auto_20190822_1423'),
    ]

    operations = [
    ]
