# Generated by Django 2.2 on 2019-05-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190504_0858'),
        ('dailyVerses', '0002_verse_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
