# Generated by Django 2.2 on 2020-01-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20200128_1759'),
        ('groups', '0006_auto_20200128_1725'),
        ('dailyVerses', '0004_auto_20200128_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedToReceiveVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReceipientMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.ExpectedToReceiveVerse')),
            ],
        ),
        migrations.CreateModel(
            name='ReceipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.ExpectedToReceiveVerse')),
            ],
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='church_groups_receiving',
            field=models.ManyToManyField(blank=True, through='dailyVerses.ReceipientGroup', to='groups.ChurchGroup'),
        ),
        migrations.AddField(
            model_name='expectedtoreceiveverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyVerses.Verse'),
        ),
    ]
