# Generated by Django 2.2 on 2020-02-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyVerses', '0005_auto_20200128_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipientgroup',
            name='receipient_group',
        ),
        migrations.RemoveField(
            model_name='receipientgroup',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='receipientmember',
            name='receipient_member',
        ),
        migrations.RemoveField(
            model_name='receipientmember',
            name='verse',
        ),
        migrations.DeleteModel(
            name='ExpectedToReceiveVerse',
        ),
        migrations.DeleteModel(
            name='ReceipientGroup',
        ),
        migrations.DeleteModel(
            name='ReceipientMember',
        ),
    ]
