# Generated by Django 2.2 on 2020-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=50)),
                ('anvil_space_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfChurchGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchGroupMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('church_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Role')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOfChurchGroups'),
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, through='groups.ChurchGroupMembership', to='member.Member'),
        ),
    ]
