# Generated by Django 2.2 on 2019-04-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipmeetingroster',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='fellowshipmeetingroster',
            name='fellowship_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.FellowshipMeeting'),
        ),
        migrations.AddField(
            model_name='fellowshipmeeting',
            name='fellowship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Fellowship'),
        ),
        migrations.AddField(
            model_name='fellowshipmeeting',
            name='host',
            field=models.ForeignKey(help_text='Names of the host being visited.', on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='cellgroupphoto',
            name='cell_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.CellGroup'),
        ),
        migrations.AddField(
            model_name='cellgroupphoto',
            name='cell_group_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.CellGroupMeeting'),
        ),
        migrations.AddField(
            model_name='cellgroupphoto',
            name='cell_group_meeting_attendee',
            field=models.ManyToManyField(blank=True, to='groups.CellGroupMeetingRoster'),
        ),
        migrations.AddField(
            model_name='cellgroupmeetingroster',
            name='attendee',
            field=models.ManyToManyField(to='member.Member'),
        ),
        migrations.AddField(
            model_name='cellgroupmeetingroster',
            name='cell_group_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.CellGroupMeeting'),
        ),
        migrations.AddField(
            model_name='cellgroupmeeting',
            name='cell_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.CellGroup'),
        ),
        migrations.AddField(
            model_name='cellgroupmeeting',
            name='host',
            field=models.ForeignKey(help_text='Names of the host being visited.', on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='minister',
            field=models.ForeignKey(help_text='minister in charge', on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
