# Generated by Django 2.2 on 2019-04-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellgroupmembership',
            old_name='cell_group_member',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='churchgroupmembership',
            old_name='church_group_member',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='fellowshipmembership',
            old_name='fellowship_member',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='ministry_members',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='ministrymembership',
            old_name='ministry_member',
            new_name='member',
        ),
    ]
