# Generated by Django 2.2 on 2019-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190416_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowshipmeeting',
            old_name='fellowship_meeting_attendees',
            new_name='attendees',
        ),
        migrations.RemoveField(
            model_name='cellgroup',
            name='minister',
        ),
    ]
