# Generated by Django 2.2 on 2020-03-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200311_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchgroupmembership',
            options={'ordering': ('-id',)},
        ),
    ]
