# Generated by Django 2.2 on 2019-04-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('groups', '0002_auto_20190405_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellgroup',
            name='cell_group_members',
            field=models.ManyToManyField(related_name='cell_group_members', to='member.Member'),
        ),
        migrations.AddField(
            model_name='fellowship',
            name='fellowship_members',
            field=models.ManyToManyField(to='member.Member'),
        ),
        migrations.AlterField(
            model_name='cellgroup',
            name='minister',
            field=models.ForeignKey(help_text='minister in charge', on_delete=django.db.models.deletion.CASCADE, related_name='cell_group_minister', to='member.Member'),
        ),
    ]
