# Generated by Django 2.2 on 2019-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190822_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfChurchGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='churchgroup',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmeeting',
            name='location',
            field=models.CharField(help_text='The location of the meeting', max_length=20),
        ),
    ]
