# Generated by Django 2.2 on 2019-08-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190822_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupOfChurchGroups'),
        ),
    ]
