# Generated by Django 2.2 on 2019-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190405_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellgroup',
            name='cell_group_members',
            field=models.ManyToManyField(blank=True, related_name='cell_group_members', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='fellowship_members',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
