# Generated by Django 2.2 on 2019-04-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190418_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellgroupmembership',
            old_name='CellGroup',
            new_name='cell_group',
        ),
    ]
