# Generated by Django 2.2 on 2019-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190419_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
