# Generated by Django 2.2 on 2019-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_churchgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='anvil_space_only',
            field=models.BooleanField(default=False),
        ),
    ]
