# Generated by Django 2.2 on 2019-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('groups', '0004_auto_20190405_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group_members', models.ManyToManyField(blank=True, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='The location of the meeting', max_length=200)),
                ('date', models.DateField(help_text='The visit date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
                ('host', models.ForeignKey(blank=True, help_text='Names of the host being visited.', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMeetingRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('group_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMeeting')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ministry_members', models.ManyToManyField(blank=True, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='The location of the meeting', max_length=200)),
                ('date', models.DateField(help_text='The visit date')),
                ('host', models.ForeignKey(blank=True, help_text='Names of the host being visited.', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryMeetingRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ManyToManyField(blank=True, to='member.Member')),
                ('ministry_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.MinistryMeeting')),
            ],
        ),
        migrations.AlterField(
            model_name='cellgroupmeetingroster',
            name='attendee',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
        migrations.RemoveField(
            model_name='fellowshipmeetingroster',
            name='attendee',
        ),
        migrations.AddField(
            model_name='fellowshipmeetingroster',
            name='attendee',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
        migrations.CreateModel(
            name='ministryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='fellowships/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Ministry')),
                ('group_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.MinistryMeeting')),
                ('group_meeting_attendees', models.ManyToManyField(blank=True, to='groups.MinistryMeetingRoster')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='fellowships/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ChurchGroup')),
                ('group_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupMeeting')),
                ('group_meeting_attendees', models.ManyToManyField(blank=True, to='groups.GroupMeetingRoster')),
            ],
        ),
    ]
