# Generated by Django 2.2 on 2020-01-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20200128_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchgroup',
            name='anvil_space_only',
        ),
    ]
