# Generated by Django 2.2 on 2020-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_churchgroup_anvil_space_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='anvil_space_only',
            field=models.BooleanField(default=False),
        ),
    ]
