# Generated by Django 2.2 on 2019-10-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190822_1433'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=20)),
                ('open', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='commentToContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=160)),
                ('votes_up', models.IntegerField(default=0)),
                ('votes_down', models.IntegerField(default=0)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.DiscussionContribution')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
