# Generated by Django 2.2 on 2019-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_channel_channelmessage_commenttocontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
