# Generated by Django 2.2 on 2019-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20191011_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
