# Generated by Django 2.2 on 2019-10-11 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191011_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
    ]
